#!/usr/bin/with-contenv bash

apk add --no-cache \
    --repository http://nl.alpinelinux.org/alpine/edge/main \
    rsync

pip install --no-cache-dir -U pip
# Make sure to install setuptools version >=36 to avoid a race condition, see:
# https://github.com/pypa/setuptools/issues/951
pip install --no-cache-dir -U setuptools>=36 urllib3[socks] flexget kinopoiskpy python-telegram-bot
