#!/usr/bin/with-contenv bash

pip install --no-cache-dir -U flexget kinopoiskpy python-telegram-bot \
&& cd /usr/lib/python3.6/site-packages/flexget/components/tmdb \
&& patch -i /patches/tmdb_lookup.py.patch
