#!/usr/bin/with-contenv bash

if [[ "$TORRENT_PLUGIN" == *"deluge"* ]]; then
    apk add --no-cache \
        --repository http://nl.alpinelinux.org/alpine/edge/testing \
        deluge

    pip2 install -U \
        constantly \
        incremental \
        service_identity
fi
