#!/usr/bin/env python3


def map_to_rip(resolution, source):
    if resolution == '2160p' and source == 'bluray':
        return '2160p UHD-Rip'
    elif resolution == '2160p' and source == 'webdl':
        return '2160p WEB-DL'
    elif resolution == '1080p' and source == 'webdl':
        return '1080p WEB-DL'
    else:
        return resolution + ' BD-Rip'


def exec_rsync(src_path, dst_path):
    from os import system

    system('rsync -rq --delete-after --size-only "{0}" "{1}"'.format(src_path, dst_path))


def main():
    from sys import argv
    from os.path import join, split, splitext

    if len(argv) < 8:
        exit(1)

    src_path = argv[1]
    dst_path = argv[2]
    title = argv[3]
    original_title = argv[4]
    year = argv[5]
    resolution = argv[6]
    source = argv[7]

    src_filename = split(src_path)[-1]
    src_extension = splitext(src_path)[-1]
    if title == '' or original_title == '' or year == '' or resolution == '':
        dst_filename = src_filename
    else:
        dst_filename = '{0} [{1}] ({2}) {3}{4}'.format(title, original_title, year,
                                                       map_to_rip(resolution, source),
                                                       src_extension)

    exec_rsync(src_path, join(dst_path, dst_filename))


if __name__ == '__main__':
    main()
